### ISSUE TITLE
getCurrentSelectionCfi() error when selection contains images.

### ISSUE THREAD

**Issue by Twibit** [readium/readium-shared-js#101]
Hello, 

I'm trying to create annotations on selected content but when i want to get the CFI of a selection containing images, i get the following Uncaught SyntaxError.

```Uncaught SyntaxError: Expected "!/", "/", "[" or [0-9] but "," found.``` in /lib/epub_cfi.js [(1483)](https://github.com/readium/readium-shared-js/blob/master/lib/epub_cfi.js#L1483)

**Comment by danielweck** [comment]
Moved:
https://github.com/readium/readium-cfi-js/issues/31

**Comment by JCCR** [comment]
Annotations_module needs to be tested with the newest CFI library.

**Comment by danielweck** [comment]
Closing as per message above from Feb 6, 2015. For any problems related to "annotations_module", please open a new issue.
