### ISSUE TITLE
How to avoid bookmarking the same page twice / Check if the current page contains a given CFI ?

### ISSUE THREAD

**Issue by Twibit** [readium/readium-shared-js#116]
Hello,

In order to avoid bookmarking the same page twice, i'd like to know if it is possible to check if a given CFI (from an existing bookmark) is visible on the currently displayed pages.
It should work even if the text's size changed or if the SyntheticSpread is toggled.

Thanks for your help

**Comment by danielweck** [comment]
@JCCR does this feature branch apply to this bug?
https://github.com/readium/readium-shared-js/tree/feature/is_element_cfi_visible

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-shared-js/issues/112

**Comment by mooshee** [comment]
Any updates on this?  The branch referenced by @danielweck is now gone 'feature/is_element_cfi_visible'.  We were using this as @JCCR described by looping through all of the bookmarks for the current spine and running "ReadiumSDK.reader.isElementCfiVisible".  That function was exposed in the aforementioned branch, but is now gone.  Is there an alternative method?

**Comment by danielweck** [comment]
@mooshee I _think_ this was merely a convenient wrapper function for `CfiNavigationLogic.isElementVisible()` (delegating to ReaderView._currentView, etc.)

@JCCR, what about the new `isElementCfiVisible()` in the refactored `CfiNavigationLogic`? (or is that superceded by another feature branch / PR?)
https://github.com/readium/readium-shared-js/blob/feature/cfi_nav_logic_refactoring/js/views/cfi_navigation_logic.js#L1089

**Comment by mooshee** [comment]
@danielweck You are correct that it was a convenient wrapper.  It appears the refactored branch handles ranged CFIs as well.

@JCCR What's the state of this feature branch?  It hasn't been touched since March 20.

**Comment by danielweck** [comment]
@mooshee it looks like @JCCR merged this to develop:
https://github.com/readium/readium-shared-js/commit/7efa8b9a4c9e30af403913ade1c2961bfa193c20

**Comment by mooshee** [comment]
Great, thanks!  Btw, this is working great for us.  Let me know if there's something I can contribute to help close this out.
