### ISSUE TITLE
Add a LICENSE in the repo root dir

### ISSUE THREAD

**Issue by pettarin** [readium/readium-shared-js#117]
Issue: deciphering which license applies to the code in the repo is not trivial. (Does the "3-clause/New BSD license" apply to the code in this repo as well as it does to that in readium-js ?)

Suggested Fix: Add a LICENSE file in the repo root directory, and maybe mention it in the README

Thanks.

**Comment by danielweck** [comment]
That was fixed a while back.
https://github.com/readium/readium-js-viewer/blob/develop/license.txt
https://github.com/readium/readium-js-viewer/blob/develop/README.md#license
