### ISSUE TITLE
Is there a way to apply the hover-* style to an annotation without clicking on it ?

### ISSUE THREAD

**Issue by Twibit** [readium/readium-shared-js#119]
I would like to select an annotation from a list in my app and display it in the content with the hover-highlight style.

Is there a way to do it ?

**Comment by danielweck** [comment]
I suggest you tweak the CSS to your liking, and your custom Javascript code can inject additional class(es) in existing annotations (i.e. `.highlight` class):

https://github.com/readium/readium-js-viewer/blob/develop/src/css/annotations.css
