### ISSUE TITLE
Custom fonts are applied after the computation of getPageForPointOnElement leading to variable results

### ISSUE THREAD

**Issue by Twibit** [readium/readium-shared-js#148]
I want to open a page (reflow) on a given element identified by a CFI. The page is using custom fonts.

If the element is at the bottom of the display and my custom font is bigger than the default one, there is a chance that the result of getPageForPointOnElement(e, x, y) vary if I request the opening from the same spine item (font already applied) or from a different one (custom font not yet applied).

**Comment by danielweck** [comment]
I thought that navigation actions were only actuated *after* the "content loaded" event (which the Readium rendering engine waits for before displaying / toggling the visibility of the iframe). Must double-check. However, I remember seeing that CSS font-face and the effective application of fonts was sometimes delayed (easy to see with some books, the text visually changes, *after* the iframe content is shown by Readium).

**Comment by JCCR** [comment]
I see this happen somewhat frequently with the Accessible EPUB sample.
