### ISSUE TITLE
Windows 8 Chrome Extension 2.16 Images breaking across columns in reflow

### ISSUE THREAD

**Issue by Kathybluefire** [readium/readium-shared-js#153]
The cover is a jpg (not a tint) and when opened it does not resize into the content window, it splits across two columns. The User Setting for Layout is Auto. 

![breaking jpg](https://cloud.githubusercontent.com/assets/4503010/5963583/6dfa4432-a7a2-11e4-9203-e3ab75d425d5.jpg)

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-shared-js/issues/138
