### ISSUE TITLE
SpineItem object in function signature for some Reader API functions

### ISSUE THREAD

**Issue by JCCR** [readium/readium-shared-js#155]
Example of issue in the code:
https://github.com/readium/readium-shared-js/blob/master/js/views/reader_view.js#L835

It is better for consumers of the Reader API (a public interface) to pass spineItem id references (string) when calling methods instead of passing SpineItem object (readium specific) references

**Comment by danielweck** [comment]
Am I right to assume that your proposed change would not impact the equivalent function signatures in other view classes? (`getElementByCfi`, `getElementById`, `getElement`)
e.g.:

https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L816

https://github.com/readium/readium-shared-js/blob/develop/js/views/fixed_view.js#L605

https://github.com/readium/readium-shared-js/blob/develop/js/views/one_page_view.js#L908

https://github.com/readium/readium-shared-js/blob/develop/js/views/scroll_view.js#L1141

**Comment by danielweck** [comment]
Fixed via PR:
https://github.com/readium/readium-shared-js/pu
