### ISSUE TITLE
reading location / bookmark contains HTML element reference + in-page visual percentage (instead of character offset)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#157]
The reading location "bookmark" that Readium saves contains 2D coordinates attached to a given HTML element, which is a broken design feature given that the visual consistency of markup in reflowable documents cannot be guaranteed from one reading session to the next (custom font size, line spacing, etc.).

Furthermore, this is an abuse of the intended feature:
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-terminating-spatial
"
3.1.6 Spatial Offset (@)

A path terminating with a leading at sign (@) followed by two colon-separated numbers indicates a 2D spatial position within an image or video. The two numbers represent scaled locations in the x and y axes, and must be in the range 0 to 100 regardless of the image's native or display dimensions (i.e., the upper left is 0:0 and the lower right is 100:100).
"

Code references:

SAVE:

`bookmarkCurrentPage()` => `getFirstVisibleElementCfi()` => `return cfi + "@0:" + foundElement.percentY`

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L603

https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L719

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L544

RESTORE:

`openBook()` => `openPageRequest.idref` (OPF spine>itemref@idref) + `openPageRequest.elementCfi` (i.e. even index + `@0:Y`, instead of odd character offset) => `openSpineItemElementCfi()`

https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L397

https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L667

... => `openPage()` => `CfiNavigationLogic.getPageForElementCfi()`

https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L386

... => `getPageForPointOnElement()` which takes (x,y) 2D coordinates

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L573

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L603

**Comment by danielweck** [comment]
Somewhat-related comment about API inconsistency:
https://github.com/readium/readium-js-viewer/issues/333

Note that @JCCR has been working on several fixes via dedicated feature branches (addressing specific pin-pointed issues), also see https://github.com/readium/readium-cfi-js/issues

**Comment by matwood** [comment]
Is there a branch where the text CFIs have been implemented? I have some internal code where we bolted on text CFIs, but I would like to either adapt and add it to Readium's `cfi_navigation_logic.js` or use what is already in process of being implemented.

Changing to text based CFIs will be a breaking change, but spatial CFIs are already broken in most cases.

**Comment by JCCR** [comment]
I have a branch: `feature/improve_cfi_accuracy`

It's an attempt to get text CFIs. You could build off of that, but the
branch is stale and there's some messy code with "outdated" techniques. We
have come up with better methods of accomplishing text CFIs, so when we got
the go ahead to contribute that I was going to start again new branch.

Therefore I would think it would be better to bring your code in to what's
on `develop`

**Comment by JCCR** [comment]
Sorry, to clarify by "we" I meant the company I work for (Evident Point)
and by "got the go ahead" I meant to say that we haven't yet but if we do
then it would start on a new branch.

**Comment by matwood** [comment]
Sounds good. Is the thought to replace the spatial offset code with text offsets or add to what is there? Internally, we (BiblioLabs) have not had a need for anything beyond the text offset CFIs, but as I bring our code in I want to stay consistent with the overall Readium architecture.

**Comment by danielweck** [comment]
Fixed by PR: https://github.com/readium/readium-shared-js/pull/210
