### ISSUE TITLE
annotations_module.js  addHighlight() ReferenceError: WebKitCSSMatrix is not defined

### ISSUE THREAD

**Issue by larsvoigt** [readium/readium-shared-js#166]
If I call the ```addHighlight()``` function in Browsers Firefox and IE, 
I get a  ```ReferenceError: WebKitCSSMatrix is not defined```. 

https://github.com/readium/readium-shared-js/blob/develop/lib/annotations_module.js#L579

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-shared-js/issues/154
(thanks @larsvoigt ;) )

**Comment by larsvoigt** [comment]
Oh yes. Thanks @danielweck.
