### ISSUE TITLE
There is no getCurrentSelectionCfi() function in reader_view.js

### ISSUE THREAD

**Issue by sajjadrad** [readium/readium-shared-js#17]
Hi
I have some problems with using Readium sdk.
There is no getCurrentSelectionCfi() or addSelectionHighlight() function in reader_view.js in master branch.so I fetched release 0.13 and replace readium-shared-js in project but after that no epub opened.
How can I use this methods for ios SDK?

Thanks

**Comment by romaingiard** [comment]
Hello,

I'm new in Readium, sorry but I didn't find highlighting functionality using the develop branch readium-shared-js. Is it still available ?

Thanks

**Comment by danielweck** [comment]
@romaingiard https://github.com/readium/readium-shared-js/issues/223
