### ISSUE TITLE
Support for EPUB3 switch is incomplete

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#171]
Issue originally raised here (MathML fallback):
https://github.com/readium/readium-js-viewer/issues/306

Partial implementation `ReadiumSDK.Models.Switches.apply`:
https://github.com/readium/readium-shared-js/blob/develop/js/models/switches.js#L28

The old Chrome extension used to "apply switches" in `iframeLoadCallback`:
https://github.com/readium/readium-chrome-extension/blob/master/scripts/views/pagination_strategies/pagination_view_base.js#L36

Now, the `iframe.onload` callback is handled differently depending on the "iframe loader strategy" (native apps, vs. cloud reader, vs. Chrome extension):
https://github.com/readium/readium-shared-js/blob/develop/js/views/iframe_loader.js#L77
https://github.com/readium/readium-js/blob/develop/epub-modules/epub-fetch/src/models/iframe_zip_loader.js#L95

..so I would suggest using the same design pattern as the overridden `updateIframeEvents` method.

**Comment by chine** [comment]
We've encountered the issue described in [readium/readium-js-viewer#306](https://github.com/readium/readium-js-viewer/issues/306) and believe we have a fix, or at least an improvement.

Submitted [PR #205](https://github.com/readium/readium-shared-js/pull/205)

**Comment by danielweck** [comment]
Thanks @chine I reviewed your PR and looks fine, but where did you hook `ReadiumSDK.Models.Switches.apply`? (`iframe.onload` callback, overridden `updateIframeEvents` method?)

**Comment by chine** [comment]
We didn't change anything else. I should say we're still on 0.18.

It's being called by the line: `ReadiumSDK.Models.Switches.apply(contentDoc);` in the callback unction of `_currentView.on(ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED` defined in `initViewForItem` of ReaderView. We've been operating in scroll-doc mode as well.

**Comment by danielweck** [comment]
@chine oh yes, of course! (`CONTENT_DOCUMENT_LOADED`)
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L228

**Comment by danielweck** [comment]
`ReadiumSDK.Models.Switches.apply(contentDoc);` is applied when the `CONTENT_DOCUMENT_LOADED` event triggered, so no need for `iframe.load`

Additionally, merged fix: https://github.com/readium/readium-shared-js/pull/205
