### ISSUE TITLE
duplicate PAGINATION_CHANGED event, updatePagination() => onPaginationChanged() (view settings / viewport resize)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#172]
Issue raised here: https://github.com/readium/SDKLauncher-iOS/issues/53

https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L667

https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L729

```
    function openPage(pageRequest, dir) {

        initViewForItem(pageRequest.spineItem, function(isViewChanged){

            if(!isViewChanged) {
                _currentView.setViewSettings(_viewerSettings);
            }

            _currentView.openPage(pageRequest, dir);
        });
    }

```

**Comment by matwood** [comment]
I was about to look into fixing this issue and see it is already in progress. Any idea when the fix will get merged into develop?

**Comment by danielweck** [comment]
Hello @matwood 
see the ongoing discussion in the pull request: https://github.com/readium/readium-shared-js/pull/174
This is on the todo list, but there is no ETA I'm afraid (we will revisit this issu at the next dev conference call)

**Comment by matwood** [comment]
@danielweck When is the conference call? Are others free to join and listen?

I'm free to bug fix, test, and do general code cleanup as needed.

**Comment by rkwright** [comment]
This week's meeting is on Tuesday, 7 July at 1600h UTC

http://www.timeanddate.com/worldclock/fixedtime.html?msg=ReadiumJS+Engineering+Meeting&iso=20150707T16&p1=%3A&ah=1

Telecon:
This meeting is using GoToMeeting

https://global.gotomeeting.com/meeting/join/334772733

Meeting ID: 334-772-733

**Comment by matwood** [comment]
@rkwright I forgot to ask on this weeks call if the meeting is the same time and meeting ID every week or if there was a mailing list or some other way to keep up to date.

**Comment by JCCR** [comment]
@matwood
It's the same ID/date every week. We have meetings for  JS on Tuesday. SDK/native on Wednesday and a bug triage/other topics on Thursday, all held at the same time of day

**Comment by rkwright** [comment]
Yes, see link here:
http://readium.github.io/meetings.html
Also, strongly urge you to join readium-dev mailing list.  Just send me an email (rkwright@geofx.com) or subscribe here: 
https://groups.google.com/forum/?fromgroups#!forum/readium-dev

**Comment by danielweck** [comment]
Fixed here:
https://github.com/readium/readium-shared-js/commit/377b3014567cbda4236df1c53734e25cac4111fa
(ensures that only the tail end of a debounced series of event callbacks is consumed)
This fixes some Media Overlays playback issues as well (as the MO engine is very sensitive to `onPaginationChanged`), such as TOC linking.
