### ISSUE TITLE
addHighlight() Cannot read property 'opener' of undefined

### ISSUE THREAD

**Issue by larsvoigt** [readium/readium-shared-js#189]
Hello, I'm lost in space.

The scenario:
For the first time, I try to highlight a cfi reference  in an unloaded spine item  
```
readium.reader.openSpineItemElementCfi(...);
readium.reader.addHighlight(...);
```
I get following exception: 
``` Cannot read property 'opener' of undefined ```

If I do the same on a loaded spine item all works fine. 
Any ideas?

**Comment by danielweck** [comment]
"unloaded spine item"?
Depending on the "iframe loader" strategy, the DOM may be garbage-collected (e.g. cloud reader => BlobURI cache is emptied to release references before opening a new spine item)

**Comment by larsvoigt** [comment]
E.g. current ```spineItem=3```, 
the cfi reference that shall be highlighted is pointing on ```spineItem=5```. 
```openSpineItemElementCfi(...)``` is working well. The right ```spineItem=5``` will be open.
Only  ```addHighlight(...)``` raise the mentioned exception. 

If I have a other cfi reference that also pointing the opened ```spineItem=5```  and 
I do call   ```addHighlight(...)``` with this cfi all works very well. 

I hope it is a little bit understandable  :-). 
thanks

**Comment by danielweck** [comment]
Are you calling `addHighlight()` from a "ready" event callback, such as `CONTENT_DOCUMENT_LOADED`?

**Comment by larsvoigt** [comment]
Thank you @danielweck. You are right! That was the reason.
I was calling ```addHighlight()``` directly after ```openSpineItemElementCfi(...)``` and 
don`t wait until the document was loaded.

**Comment by dmitrym0** [comment]
Typically you have to wait for the whole document to load. If you do `openSpineItem..` and then immediately `addHighlight` you'll end up in a state where the document hasn't been fully loaded yet. That's most likely the reason your highlight is failing.
