### ISSUE TITLE
Is Readium going to support Scriptable Component ?

### ISSUE THREAD

**Issue by Twibit** [readium/readium-shared-js#197]
The IDPF is currently working on the specification of [Scriptable Components](http://www.idpf.org/epub/sc/pkg/).
Is Readium planning to support those components ? Do you have an idea on when this should be available ?

**Comment by rkwright** [comment]
Yes, we are.  I (Ric Wright) am a member of that working group.  I have been in fact creating some sample widgets.  The code is here:
https://github.com/IDPF/scriptable-components/tree/feature/logger-widget

These widgets work in the Chrome Extension, OSX, iOS and Android, though the behaviour in iOS is a bit funky. See issue here: https://github.com/readium/SDKLauncher-iOS/issues/60

Note that I use WebStorm to code the widgets, so there is a WebStorm project (.idea folder) for the tempwave-demo (but not the individually packaged widgets).

The writeup is here:
https://docs.google.com/document/d/1jffqS4xyvLhrfH_UR3XFILwPgZbhfe1098lP7UwxMAs/edit#

Please let us know if you have questions or suggestions.

**Comment by rkwright** [comment]
Closing as answered.

@Twibit  : Let me know if you need more info or wish to contribute.
