### ISSUE TITLE
Changing from single to double page spread does not take effect.

### ISSUE THREAD

**Issue by mooshee** [readium/readium-shared-js#214]
Steps to reproduce:
1. Open moby-dick-20120118.epub --> Spine Items --> xchapter_001
2. Ensure Synthetic Spread is set to Single
3. Open settings
4. Set Synthetic Spread to Double
5. Observe single page spread (appears to be only show the first page/column of the spread)

NOTE: Reloading the spine or loading a new spine (by arrowing to the next chapter) fixes the layout.

Test environment:
SDKLauncher-IOS, branch --> feature/wkwebview
iPhone 6 iOS 8.4 Simulator
moby-dick-20120118.epub --> Spine Items --> xchapter_001

Settings printed from `<NSDictionary *settings>` in `<passSettingsToJavascript>`

Before:
    columnGap = 20;
    fontSize = 150;
    scroll = auto;
    syntheticSpread = single;
![before - single spread](https://cloud.githubusercontent.com/assets/874270/9971830/e4ddd366-5e2c-11e5-9514-b8f27dfd5b41.png)

After:
    columnGap = 20;
    fontSize = 150;
    scroll = auto;
    syntheticSpread = double;
![after - double spread](https://cloud.githubusercontent.com/assets/874270/9971831/eaebae0e-5e2c-11e5-8f42-63b010f96e98.png)

Expected result: (can be achieved by reloading the spine)
![expected - double spread](https://cloud.githubusercontent.com/assets/874270/9971885/6a28f852-5e2d-11e5-832f-76badcdf44ed.png)

**Comment by danielweck** [comment]
Thank you for reporting this (screenshots help!)
This should be fixed now: https://github.com/readium/readium-shared-js/issues/216
Please re-open this issue if you still experience this problem.
