### ISSUE TITLE
reader.updateSettings({syntheticSpread: value}) does not update layout

### ISSUE THREAD

**Issue by pmstss** [readium/readium-shared-js#220]
I think resetCurrentView() should be called in this case inside initViewForItem(), but earlier exit happens after deduceDesiredViewType() call and comparing returned value with existing. That values are equal, because  deduceDesiredViewType() doesn't take changed syntheticSpread value into account.
So condition for calling resetCurrentView() seems to be wrong.

**Comment by danielweck** [comment]
Hello, this seems to work fine in the "cloud reader":
http://development.readium.divshot.io

Could you please explain the steps to reproduce this bug?
Many thanks!

**Comment by pmstss** [comment]
i meant just calling `reader.updateSettings({syntheticSpread: 'single' / 'double' / 'auto'})` from browser console.
i tried with cloud reader - can't reproduce something similar there.
and i can't reproduce it in own app anymore after updating readium-related part from master to develop branch. 
sorry, perhaps it was just some old issue in master.
