### ISSUE TITLE
Image cut 

### ISSUE THREAD

**Issue by romaingiard** [readium/readium-shared-js#234]
Hello,

When an image is higher than the screen height it's cut, moreover when an image is in the bottom of a page it's also cut.
Is it possible to avoid this behaviour ?

Thank you.

**Comment by danielweck** [comment]
Hello @romaingiard this is a known problem with CSS Columns (which Readium uses to implement "book-like" visual pagination). Please take a look at the existing issues (and discussion threads), and let us know if you have thoughts / ideas on how to consistently constrain the image size depending on its wrapping context (ancestor HTML elements and CSS styles).
https://github.com/readium/readium-shared-js/issues/138
https://github.com/readium/readium-shared-js/issues/64
https://github.com/readium/readium-shared-js/issues/88
https://github.com/readium/readium-shared-js/issues/144
There's also a Pull Request here:
https://github.com/readium/readium-shared-js/pull/173
