### ISSUE TITLE
User encounters browser error when opening test books in firefox or safari

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-shared-js#243]
student testers report Safari browser error of "Safari cannot open the page because the address is invalid" when attempting to open test books in Safari from  iPad4G- iOS-6.0.1.
I was able to reproduce this error in Safari and Firefox on my 64 bit Win 7 Pro desktop browsers as well as our iPad air. 
Daniel & Ric have suggested this may be a network firewall issue and is now being investigated by our in house tech support team. updates to follow...

![image](https://cloud.githubusercontent.com/assets/7536426/12122671/7aca6dee-b3aa-11e5-8bcc-5d5bbf53d2bd.png)

**Comment by danielweck** [comment]
Thanks @duanwalker 
Given that we now know that this is due to firewall issues (invalid SSL HTTPS certificates), should we close this issue?
Dan

**Comment by rkwright** [comment]
I would suggest that we wait for Duan to update the Testing document with the proper approach for ensuring testers don't run into this problem, then he can close it.

**Comment by rkwright** [comment]
@duanwalker Thanks for updating the doc.  Closing.
