### ISSUE TITLE
SVG in spine CFI navigation logic fails

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#248]
Uncaught TypeError: Failed to execute 'createNodeIterator' on 'Document': parameter 1 is not of type 'Node'.

To reproduce: Readium build from develop (includes CFI "Intel improvements"):
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub3-samples%2Fmaster%2F30%2Fsvg-in-spine

Compare with working Readium build from master (old CFI "navigation logic"):
https://readium-master.surge.sh/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub3-samples%2Fmaster%2F30%2Fsvg-in-spine

Thanks @JCCR :)

**Comment by JCCR** [comment]
Looking into it.

**Comment by JCCR** [comment]
@danielweck Unrelated: Are the jpeg images in the SVG spines (with xlink:href) supposed to be not working?

**Comment by JCCR** [comment]
Fixed in 3ee4844

**Comment by danielweck** [comment]
@JCCR `xlink:ref` requires a `xml:base` or `html>head>base@href` when the SVG document is loaded as a BlobURI. Unfortunately support for both `xml:base` and `base@href` is broken in SVG (known browser issues, unrelated to Readium). I am investigating different ways to address this.

**Comment by danielweck** [comment]
Thanks @JCCR I am closing this issue, but I am opening a separate one for SVG scaling issues (SVG-in-spine)

**Comment by danielweck** [comment]
Juan's fix tested at: https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub3-samples%2Fmaster%2F30%2Fsvg-in-spine

Note that SVG-embedded images (xlink-ed) fail to resolve against the base URI, this is a know issue:
https://github.com/readium/readium-shared-js/issues/251
