### ISSUE TITLE
TOC navigation broken (headings inside spine item)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#253]
@JCCR do you think this is a CFI "navigation logic" issue?
Try "Accessible EPUB3":
https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Faccessible_epub_3
...open the TOC, and link-click into any heading under "2. Building a Better EPUB: Fundamental Accessibility".
This works fine in Chrome, but fails in Firefox, Internet Explorer and Edge! :(

**Comment by JCCR** [comment]
Fixed in a110d5f.

Tested in Firefox.

@danielweck Could you test on IE/Edge for me and close this when done? Thanks

**Comment by danielweck** [comment]
The fix is working great @JCCR Thank you!
Tested on Windows 10 in: Chrome, Firefox, Edge and Internet Explorer.
(PS: there is still the issue of CPU spike in IE, laggy TOC linking, see https://github.com/readium/readium-shared-js/issues/247 )
