### ISSUE TITLE
cloud reader demo dosent work

### ISSUE THREAD

**Issue by hz0324** [readium/readium-shared-js#254]
as the tile

**Comment by danielweck** [comment]
The Readium web reader app (built from the develop branch) is working well at the following deployment sites:

https://readium.firebaseapp.com

https://readium.surge.sh/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_library.opds

If you wish to build your own app, please follow the instructions in the README:

https://github.com/readium/readium-js-viewer/blob/develop/README.md

I am closing this issue, but please feel free to re-open and/or add more information.

**Comment by hz0324** [comment]
Thanks, it is really great.
I guess youd better change the link of cloud reader on Project home page, which is not working now. As bellow
http://development.readium.divshot.io

**Comment by danielweck** [comment]
Thank you!
What project homepage is this link available from?

http://readium.github.io

http://readium.org

Else?

**Comment by hz0324** [comment]
right here: https://github.com/readium/readium-js-viewer
please see the screenshot
![1232131](https://cloud.githubusercontent.com/assets/5040078/12866891/de2ce600-cd18-11e5-9caa-cdc9fe8dd0ea.png)

**Comment by rkwright** [comment]
Fixed in the develop branch readme.md

**Comment by danielweck** [comment]
@rkwright I suggest the following corrections:
https://github.com/readium/readium-js-viewer/commit/8335715a1c91757a45aef9ebbbddbdbac1184eb5#diff-04c6e90faac2675aa89e2176d2eec7d8
