### ISSUE TITLE
Bookmarks broken on iOS, contentCFI always null

### ISSUE THREAD

**Issue by olivierkorner** [readium/readium-shared-js#257]
When creating a bookmark on iOS in a reflowable book, the contentCFI part of the bookmark structure returned by bookmarkCurrentPage is always null.

Digging a little deeper revealed that getCaretRangeFromPoint() always returns null.
https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L112

**Comment by JCCR** [comment]
Looking into this but I might need some more info as to which books or the type of content that was tested.

**Comment by rkwright** [comment]
@olivierkorner Does this problem occur with the EPUB you shared with Daniel Weck and I (Walter Bennet)?  Would it be OK for me to share that EPUB with Juan so he can look at this problem?  He will not distribute the EPUB.

**Comment by olivierkorner** [comment]
@rkwright Yes it occurs with any reflowable EPUB I've tried. 
of course, it's OK, you can share it with Juan, no problem.

**Comment by olivierkorner** [comment]
This may be an issue with webkit. Looking for similar issues with getCaretRangeFromPoint, I found this:
https://bugs.chromium.org/p/chromium/issues/detail?id=263813
And indeed, I add "webkit-user-select: none" on <html> elements in my implementation.
Removing it seems to solve the issue.

**Comment by JCCR** [comment]
Interesting find. The more I test the code that uses caretRangeFromPoint
the more I find that it's buggy and not 100% stable, which is fair it is
still experimental..

I'm going to start looking into an alternative or fallback method.

**Comment by jce1028** [comment]
We are seeing this in NYPL as well.  The book consistently return a few paragraphs/lines prior to where the bookmark was placed

**Comment by mooshee** [comment]
+1

@JCCR It appears that only the first page of each spine is able to be bookmarked.  I'm running the latest from develop.

**Comment by JCCR** [comment]
Started work on an alternative method for improved IE11 support (maybe it might help iOS too). I'll double down on reproducing this on my end using iOS.

**Comment by JCCR** [comment]
Confirmed that this is broken on iOS and Safari, but not Chrome/Firefox when `user-select: none` is used

**Comment by xieweizhi** [comment]
@JCCR 

Hey,  I'm working on a bookmark feature on iOS.  It's ok when calling `openSpineItemElementCfi` . After this I open the next page , the webView is totally blank. Do you have any idea why ?

**Comment by rkwright** [comment]
Closing as stale
