### ISSUE TITLE
Continuous scroll option is not working

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#258]
The option to reflow an entire EPUB into one long galley document is currently broken.  Instead of concatenating all the spine items into one long galley, Readium concatenates some limited number (like 2 or 3 spine items) then stops.  In fact, you can't even navigate past the point where it stops.  If you try to choose the next spine item after that stoppage (via the TOC), Readium apparently re-paginates and then stops at the same place.

Tested in both the CloudReader 0.23-alpha and the Chrome Extension currently in the Chrome Store 2.22.2.  Tests run on MacBook Pro, OSX 10.10. Happens with all reflowable books tested, including Alice in Wonderland and the [EPUB Test Suite 100](http://www.epubtest.org/epubs/epub30-test-0110-20160116.epub).

**Comment by danielweck** [comment]
This is working fine in my Chrome web browser on Android 6

https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Faccessible_epub_3

..it's the latest cloud reader app build from develop, which includes the jQuery regression bug fix. Could you please try again? (in your desktop browser)

Thanks!

**Comment by rkwright** [comment]
That seems to work on my MBP with Chrome, Safari and Firefox.  But it is broken in the current Chrome Extension on the store.  Let's discuss briefly in the eng meeting tomorrow.

**Comment by danielweck** [comment]
Sounds like jQuery 2.2.0 which breaks the '.position()' function. Fixed in the develop branch:

https://github.com/readium/readium-shared-js/compare/5693ddf514d1f47326c479ad791705be14a6dd00...d8e3da04e489c84376921c58134f1e9ff3834a20

See:

https://github.com/readium/readium-cfi-js/pull/48#issuecomment-184581089

**Comment by rkwright** [comment]
Verified that it is fixed in the current 2.23-alpha build on github/releases

**Comment by danielweck** [comment]
Thanks Ric! Can this issue be closed now?

**Comment by rkwright** [comment]
Sorry, folks, more testing is showing some serious issues.  If I open Alice 3 EPUB, and use continuous scrolling mode in 2.22.3 it seems to work fine.  BUT if you look closely, you'll note that the page-arrows are still displayed. And if you press them it takes you to somewhere a couple of "pages" ahead of where you are in the current "page".  It looks like it is essentially switching to a new column or something and doing a normal page-turn's worth of advancing.

Worse, if you select scroll-doc, it presents the page-turn arrows, and they work, but instead of taking you to the next spine item, it just shows the same spine item again.  And, if you had been in paginated or continuous mode and went to spine item 6, then you're stuck in spine item 6.

So our scroll support is still seriously broken.  We can't release this. I have bumped the priority to blocking.

**Comment by danielweck** [comment]
Continuous and per-document scrolling view seems to work just fine in my tests:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3
(Chrome browser, Windows 10)

I have been able to "get stuck" when using the mouse / trackpad scroll
gesture, because the HTML scroll control sometimes does not respond when there's no remaining pixels to move.
However I have never experienced this with arrow keys (i.e. previous/next "page", which the scroll view does perfectly well, in a keyboard-accessible way).

Maybe I do not understand the issue?

**Comment by rkwright** [comment]
No it is clearly broken.  I just tried Accessible EPUB and it looks OK UNTIL you go to Chapter 1 which is longer.  Then you're stuck in Chapter 1.

**Comment by danielweck** [comment]
@rkwright I am afraid I am not able to reproduce the problem you describe, so I can't help debug this issue right now. I will make further attempts with other web-browser / window-size / font-size dimensions. I will let you know if I find anything conclusive. Thanks @JCCR for looking into this too! :)

**Comment by rkwright** [comment]
OK, now I see what is happening.  When I open a reflowable document and
set document scroll mode.  I see the start of a spine item. I can scroll
up and down in that spine item. I hit the arrow key and what Readium does
is scroll DOWN a page in the current spine item.  If I keep hitting the
arrow key I go down in the spine item and when I reach the end of spine
item it loads the next spine item.  That’s not what the EPUB TestSuite
expects, but the spec isn’t really clear:

*EPUB 3.0.1 4.4.1.2.2 Allowed values*
The Reading System should render all Content Documents such that overflow
content is scrollable, and each spine item should be presented as a
separate scrollable document.

*EPUB Test Suite 111:*
If each of the documents in this publication is vertically scrollable, and
swiping horizontally moves from one to the next, the test passes.

So what the EPUB Test Suite expects is behaviour like Adobe’s DPS where
horizontal navigation is BETWEEN “spine items” and vertical navigation is
WITHIN the spine item.

Note that the behaviour with continuous scrolling is the same, the arrows move you down one page.

So we’re not doing it quite right, but the spec isn’t really clear, so I
think we’re OK.

**Comment by danielweck** [comment]
Yes, from the very beginning, Readium's scroll-view implementation always considered that the page previous/next commands (i.e. arrow keyboard shortcut, left/right user interface button, horizontal swipe touch gesture, etc.) would "paginate". In the specific context of a vertically (or horizontally) scrolling viewport, this means offsetting / panning the content by a distance corresponding to the height (or width) of the visible part of the viewport. This way, keyboard users (i.e. those not interested in using the scrollbar directly) can efficiently navigate the linear content stream.

**Comment by rkwright** [comment]
Fixed with release of Chrome Extension 2.22.3
