### ISSUE TITLE
Max column width for reflowable documents is too narrow

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#259]
If I have a reflowable document we layout the document in a very narrow column no matter if single or double spread is set.  Only if one selects  scroll-doc or scroll-continuous do we use most or all of the width available.  This is true both on the desktop and the tablet (iPad).

The width is so narrow it looks bad.  In my WebGL tutorial I can’t even get 64 columns of monospace on the screen unless I make it pica-sized.  It’s essentially unusable.  

In reflow-view.js I see on line 554:

       // At 100% font-size = 16px (on HTML, not body or descendant markup!)
        var MAXW = 550; //TODO user/vendor-configurable?
        var MINW = 400;

So the maximum width is apparently set to 550 pixels.  If I modify the code and set it to the typical tablet width of 768, then it is MUCH better.

So there seem to be several issues:
- the maximum column width is too narrow
- we enforce this maximum column width in paginated reflow layout, but not in the scrolled view.  This seems wrong.

**Comment by JCCR** [comment]
I don't like that this exists in the pagination flow. In our customized
Readium for EP has this disabled. But I understand the original purpose,
maybe we need to have it vendor configurable like in the TODO comment.

**Comment by rkwright** [comment]
@JCCR Could you elaborate?  If EP has it disabled, what, exactly, is disabled?  How is the appropriate column width calculated?  What Readium is doing now is wrong, IMO, so let's figure out what is right.

**Comment by danielweck** [comment]
@rkwright last time I checked, Readium and iBooks (OSX) rendered reflowable documents using very similar pagination thresholds. That being said, based on user and vendor feedback (EvidentPoint, BlueFire, etc.) it is quite clear that this behaviour needs to be configurable. IMO disabling this completely in Readium would alienate users who struggle to read wide runs of character across pages. As always, the main problem is to use sensible defaults that meet the majority's needs. PS: many WordPress / web page templates for text-heavy content use similar max-width styling strategies (Readium attempts to scale proportionally with font size, to approximate an optimal number of characters/words per line run). What's frustrating for users is when they have no option to configure. Let's fix that.

**Comment by rkwright** [comment]
@danielweck 
  I agree that it should be dynamic.  Only that our default and the maximum aren't, IMO, correct.  I'll do some more comparisons with iBooks and also Android.

**Comment by rkwright** [comment]
OK, this is getting weirder.  Not done testing, but what I am seeing is with different values of MAXW:
* OSX: A bit too narrow at 550 (~74 chars), but looks fine at 768
* iOS:   Way too narrow at 550, but changing MAXW doesn't make any difference?  What??
* Chrome Extension:  Too narrow at 550 but looks fine at 768
* Android:  Too narrow (~61 chars) at 550,and changing it to 768 didn't seem to make any difference??  And  it only renders the monospace text on the first page?! Subsequent pages are blank!

_[Contact Ric for a copy of the EPUB]_

**Comment by danielweck** [comment]
Thanks Ric. I get 70-90 chars between 500-700 px page width (cloud reader / Chrome app), but of course this is highly dependent on font size (maybe even custom DPI settings on high-res displays?). By the way, Readium nullifies the margin/padding of reflowable EPUB content documents' HTML/BODY, as an attempt to make the application of the CSS Column gap (aka margin) more consistent.

**Comment by danielweck** [comment]
@rkwright you may try https://github.com/readium/readium-shared-js/tree/feature/pageWidth and https://github.com/readium/readium-js-viewer/tree/feature/pageWidth (includes new config UI for page width, replaces bogus columnGap / margin)

**Comment by JCCR** [comment]
@rkwright 
We disable it in EP's code because we feel like the container for rendering from Readium's side should try to take up the maximum amount of space, and the responsibility of setting page margins should be up to the viewer controlling the "canvas". If it needs to be dynamic then the viewer code should control this canvas by taking information or signals from Readium. This gets tricky because the process needs to be coordinated and tightly involved with how we do pagination for reflowable page rendering.

**Comment by rkwright** [comment]
@JCCR  Disable it how?  In some fashion similar to what Daniel did in his feature branch?  Or set MAXW to 15 million?  Or?

**Comment by JCCR** [comment]
@rkwright 
Commented out this line:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L649

**Comment by danielweck** [comment]
Hello @JCCR so I imagine that your userbase either:
- does not go full screen / maximized browser window (on wide / high-dpi displays)
or:
-  does the above, but does not mind high number of characters per line of text?

At any rate, the feature branch addresses this by exposing a simple preference control (UI slider) to allow users to configure their preferred behaviour (the page width limit can be disabled altogether). I increased the value of the "sensible default" for the optimal page width, but depending on font size and word spacing, mileage can vary.

**Comment by danielweck** [comment]
@JCCR PS: I agree about the viewer taking charge of "margins" (i.e. blank spaces on either side of the content viewport, available for UI controls / application chrome). However I believe that the pagination engine (in readium-shared-js) should expose properties such as "max page width" (which is not proportionally related to margins) to ensure a consistent experience across platforms.
Thoughts welcome of course.
As Ric said, the feature can be disabled entirely by setting the max value to a large positive integer.

**Comment by rkwright** [comment]
I commented out the line per Juan's suggestion.  In testing on OSX with my MBP and a cinema display, when full screen is invoked, the display goes to a synthetic spread (two columns) each about 800-900 px wide.  Wasn't too wide for me, but others might find it a bit wide.  But it wasn't, IMO, horrible.  And that's a pretty extreme case (full screen on a huge display).

**Comment by danielweck** [comment]
Addressed via PR: https://github.com/readium/readium-js-viewer/pull/498

Test:

https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2635343%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bbuilding_a_better_epub%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

Go fullscreen on your wide display.

In the application's preferences, choose single-page. Take a mental
note of the default page width value (mouse hover to see the actual
CSS pixels value). Save settings.

Re-open settings, move the page width cursor all the way to the right
("disabled" state). Enjoy mile-long lines of text :)

Also try the smallest value, just out of interest.

TODO Discuss: optimal low/high values.

**Comment by rkwright** [comment]
Re optimal values, the standard tablet width is 768 pixels (or 1536, etc.) but with a reasonable margin the  right value is probably around 730-740.  But that is for a single column.  Might be too wide for sum, but my EPUBs with formatted code in them with monospaced fonts, using 72 characters across work well at that width. If the width is less than that you have to shrink the font down to teeny-tiny.  Just my two cents.
