### ISSUE TITLE
reflowable first page is temporarily shown (flash) when last page is reached from next spine item

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#271]
To reproduce, open:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Frawgit.com%2Fdbelinson%2FsimpityReader%2FnewOnlyOneBook%2Fapp%2Fsrc%2Fmain%2Fassets%2Fpushkin_.epub&goto=%7B%22idref%22%3A%22bookcontent294_0%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bt_d01471%5D%2F2%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

...and press the "previous page" button (or hit the left arrow key).

**Comment by danielweck** [comment]
I forgot to say: the EPUB is in Cyrillic (I think), but this is probably not the cause of the pagination event "latency".
Source: https://github.com/dbelinson/simpityReader/blob/newOnlyOneBook/app/src/main/assets/pushkin_.epub

**Comment by rkwright** [comment]
I cannot reproduce this on OSX 10.10 in Chrome.  Version 48.0.2564.116 (64-bit)

**Comment by danielweck** [comment]
I am able to reproduce this rendering behaviour on Windows 10 with Chrome (100% repro rate), Firefox (95% repro, estimated :) ), but Edge and Internet Explorer do not seem to exhibit this problem.

**Comment by danielweck** [comment]
Fixed here:
https://github.com/readium/readium-shared-js/commit/3a1709b3507c11be45876ab2c0832b8d1560e3a8
