### ISSUE TITLE
Missing the Online "cloud reader" demo

### ISSUE THREAD

**Issue by elEglon** [readium/readium-shared-js#281]
Dear reader,

As I want to get into contact with Readium as a cloud solution, I tried to open an example, but the demo is gone.

Would you please be that kind and tell me, if there is an other demo online?

Thank you and best wishes 
Eglon

**Comment by danielweck** [comment]
Hello, it looks like you have an obsolete link? (DivShot.io?)
The correct URL is:
https://readium.firebaseapp.com
Alternatively:
https://readium.surge.sh/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_library.opds

**Comment by rkwright** [comment]
@elEglon Can you please take a look at the instructions in the readme.md here:
https://github.com/readium/readium-js-viewer
Is this what you were looking for?  If not, could you provide some more specific information about what you are interested in?
Also, please see:
https://docs.google.com/document/d/1bwv89vSmLbUs4tHOwiqyeV546k5CG3RCJ1S6_-4wvvc/edit#heading=h.84j3ouqlcuoa

**Comment by elEglon** [comment]
Thank you very much for your fast and kind support!

Best wishes
Eglon
