### ISSUE TITLE
 Get CFI of a scentence in the epub-book

### ISSUE THREAD

**Issue by Seanberite** [readium/readium-shared-js#286]
Is it possible to extract the CFI of a word or string that is on the page given the specific xhtml file and the specific sentence. I'm implementing a search function and I already know that the specific sentence is on the page, but i need to extract the CFI.

**Comment by danielweck** [comment]
Hello, I see you've already started working with @larsvoigt 's `epub-full-text-search` project:
https://github.com/Seanberite/epub-full-text-search/commits/master

Let's join @JCCR to this discussion.
You can convert user selections and DOMRanges via Readium's CFI API, but I'm not sure about doing this without loading the HTML document into a webview (i.e. from the DOM). I assume you want to load raw HTML files (plain text source), maybe parse the markup on the server side (NodeJS)?

**Comment by larsvoigt** [comment]
Hello,
thanks @danielweck  for cc'ed me,

I think the intension is, that ```epub-full-text-search``` (server)  should only deliver the partial cfi (e.g. “/6/6[c01ref]! -> spineitem ref) of any search query and than complete cfi on the client (readium cloud reader). 

The question to the readium developers could be: 
After the specific spineitem (navigation to partial cfi) is loaded (readium client). 
Is it than possible to pass any query (word and also sentence)  to the readium cfi api , to get the tail of cfi (content reference) ?  Then the query can be highlighted via completed cfi .
@Seanberite correct me if I´m wrong.  


PS.:
Generelly good idea if it is your meaning @Seanberite. 
The advantage could be, there is no need for a local copy of epub-file on the server.
