### ISSUE TITLE
apidocs npm build step fails to pick up all params

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#297]
#### This issue is a Bug

Our build system based on node (npm) has a build step named _apidocs_.  It reads all the JS code and extracts the annotated methods and parameters etc and generates HTML documentation.

#### Related issue(s) and/or pull request(s)
None

#### Expected Behaviour
The build step should read all the source code and generate appropriate HTML output

#### Observed behaviour
The yuidoc-based scripts do NOT pick up all the annotated parameters.  See spinItem for example

#### Steps to reproduce
1.Get a complete copy of the readium-shared-js repo.
2. run _npm run prepare_ then _npm run apidocs_
3. Open the file _apidocs/index.html_
4. Select spineItem 
5. Observe that there is no content for spineItem. Compare to jsdoc (see below)

#### Screen shots
**yuidoc result:**
![yuidoc-spineitem](https://cloud.githubusercontent.com/assets/3025864/16017960/f135be6c-3167-11e6-8adf-0c285a887134.png)

**jsdoc result**
![jsdoc-spineitem](https://cloud.githubusercontent.com/assets/3025864/16017977/0861d63e-3168-11e6-86bf-c80a4900b206.png)

### Product
All

#### Additional information
Works fine with jsdoc

**Comment by danielweck** [comment]
wow! a blank line!?
thanks for looking into this.

**Comment by rkwright** [comment]
Right, so we have to choose whose syntax to support.  We are currently using yuidoc and I kind of like their output a bit better.

BTW, I worked with yuidoc a while ago and tweaked their Hogan mustache code to get a more Readium-like output, i.e. akin to the Readium.org site (colors, etc.)  Of course, now we (Sarah) has rewritten the site but I'll take a look at what I did then and see if any of it is worth salvaging.

I will also start updating the "how to generate the api-docs" document [here](https://docs.google.com/document/d/1BKPLoe5J2okvvxV4FqvrsAiywvtimphzIXSwHtKuRho/edit) and put in the proper syntax for yuidoc.

**Comment by danielweck** [comment]
`readium-js-viewer`:
https://github.com/readium/readium-js-viewer/blob/develop/yuidocs.json

`readium-js`:
https://github.com/readium/readium-js/blob/develop/yuidocs.json

`readium-shared-js`:
https://github.com/readium/readium-shared-js/blob/develop/yuidocs.json

`readium-cfi-js`:
https://github.com/readium/readium-cfi-js/blob/develop/yuidocs.json

**Comment by danielweck** [comment]
Related PR (now merged): https://github.com/readium/readium-shared-js/pull/329

**Comment by llemeurfr** [comment]
The doc has been moved to the jsdoc syntax using the indications given by Ric on 
https://docs.google.com/document/d/1BKPLoe5J2okvvxV4FqvrsAiywvtimphzIXSwHtKuRho/edit 

Therefore I believe that this issue can be closed.

Note that the jsdoc syntax mandates a @constructor decorator.
