### ISSUE TITLE
ScrollView isn't using any font loading mechanism

### ISSUE THREAD

**Issue by olivierkorner** [readium/readium-shared-js#312]
#### Related issue(s) and/or pull request(s)
#300

https://github.com/readium/readium-shared-js/pull/304
https://github.com/readium/readium-shared-js/pull/308
#### Expected Behaviour

View should make sure the fonts are loaded before layout, or update layout on font load.
### Product

All

**Comment by danielweck** [comment]
Also note that the OpenDyslexic / custom font feature branch implements a change in where the FontLoader "wait" function is invoked (not just to detect authored fonts at load-time, but also user-specified fonts at read-time). See:
https://github.com/readium/readium-shared-js/pull/301/files#diff-5899c9a9fc900e9651da6e2d81f3025bL223

**Comment by olivierkorner** [comment]
@danielweck The resize sensor should be able to detect if the pagination needs to be updated following the loading and rendering of the text with the user-specified font, thus removing any need for FontLoader here as well.

**Comment by danielweck** [comment]
Fixed in the `develop` branch, see:
https://github.com/readium/readium-shared-js/pull/308

Relevant code references:

https://github.com/readium/readium-shared-js/blob/develop/js/views/one_page_view.js#L386
```javascript
            var bodyElement = _$epubBody[0];
            bodyElement.resizeSensor = new ResizeSensor(bodyElement, function() {
                console.log("OnePageView iframe body resized", $(bodyElement).width(), $(bodyElement).height());
                var src = _spine.package.resolveRelativeUrl(_currentSpineItem.href);
                Globals.logEvent("OnePageView.Events.CONTENT_SIZE_CHANGED", "EMIT", "one_page_view.js [ " + _currentSpineItem.href + " -- " + src + " ]");
                self.emit(OnePageView.Events.CONTENT_SIZE_CHANGED, _$iframe, _currentSpineItem);
                //updatePagination();
            });
```

https://github.com/readium/readium-shared-js/blob/develop/js/views/scroll_view.js#L560
```javascript
        pageView.on(OnePageView.Events.CONTENT_SIZE_CHANGED, function($iframe, spineItem) {
            
            Globals.logEvent("OnePageView.Events.CONTENT_SIZE_CHANGED", "ON", "scroll_view.js [ " + spineItem.href + " ]");
            updatePageViewSizeAndPagination();
        });
```
