### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by looknear** [readium/readium-shared-js#334]
sh: 1: node: not found

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "clean"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! readium-shared-js@0.24.0 clean: `node --version && npm --version && node ./readium-cfi-js/node_modules/rimraf/bin.js build-output/* && node ./readium-cfi-js/node_modules/rimraf/bin.js api-docs/*`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the readium-shared-js@0.24.0 clean script 'node --version && npm --version && node ./readium-cfi-js/node_modules/rimraf/bin.js build-output/* && node ./readium-cfi-js/node_modules/rimraf/bin.js api-docs/*'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the readium-shared-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --version && npm --version && node ./readium-cfi-js/node_modules/rimraf/bin.js build-output/* && node ./readium-cfi-js/node_modules/rimraf/bin.js api-docs/*
npm ERR! You can get information on how to open an issue for this project with:

**Comment by danielweck** [comment]
Did you invoke "npm run prepare" first and foremost?

**Comment by looknear** [comment]
This error cam at the end of prepare.
then i run install and update separately which look ok.
then build - got this error.
Ubuntu 16 - 64b

**Comment by danielweck** [comment]
Oh, I just noticed that you have NPM v3, you need v2 (Node itself is alright at v4, just don't use the new NPM flat node_module structure).
See: https://github.com/readium/readium-js-viewer/issues/453

**Comment by looknear** [comment]
ok. will try again. I'm new with Node. sorry.
hope that after i will understand the architecture and will get familiar with the code - i will be able to contribute more, especially to the RTL improvements which i see are needed.
