### ISSUE TITLE
Update MathJax to v2.7

### ISSUE THREAD

**Issue by pkra** [readium/readium-shared-js#351]
The MathJax single-file build is now using MathJax v2.7, cf. https://github.com/pkra/MathJax-single-file/commit/0e502cebfc7de48da2265ead66b5a562c864b62d.

**Comment by danielweck** [comment]
Thanks for the heads-up!
The cloud reader app is building:
https://travis-ci.org/readium/readium-js-viewer/builds/178810423
...as usual, will be deployed at Firebase and Surge:
https://readium.firebaseapp.com
https://readium.surge.sh

**Comment by danielweck** [comment]
MathJax 2.7 seems to work fine:
https://readium.firebaseapp.com/?epub=epub_content%2Flinear-algebra&goto=%7B%22idref%22%3A%22c9%22%2C%22elementCfi%22%3A%22%2F4%5Bx10-9000%5D%2F4%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D
