### ISSUE TITLE
Cfis/range that spans across two direct children of body fails in cfi_navigation_logic.js

### ISSUE THREAD

**Issue by einarstubhaug** [readium/readium-shared-js#353]
#### Related issue(s) and/or pull request(s)
https://github.com/readium/readium-cfi-js/issues/54

If a range spans across two direct children of body, calling the function isRangeCfi in cfi_navigation_logic.js causes an error

#### Steps to reproduce
1. First, use generateCharOffsetRangeComponent or similar in epubCFI to create a partial cfi spanning two direct children of body, e.g '/4,/36/1:170,/38/1:3'
2. Then e.g call openSpineItemElementCfi in reader with this cfi as parameter. Readium throws an error

This is the code in question: (cfi_navigation_logic.js)
this.isRangeCfi = function (partialCfi) {
        return EPUBcfi.Interpreter.isRangeCfi(getWrappedCfi(partialCfi)) || EPUBcfi.Interpreter.isRangeCfi(getWrappedCfiRelativeToContent(partialCfi));
    };

isRangeCfi converts/wraps the partialCfi to a full cfi for it to parse. It first tries wrapping with method getWrappedCfi. The cfi is converted to "epubcfi(/4,/36/1:170,/38/1:3)", but an uncaught error is thrown by the parser as this is not a valid cfi. If it had been wrapped it with getWrappedCfiRelativeToContent, the cfi would have been converted to "epubcfi(/99!/4,/36/1:170,/38/1:3)" which is valid.
    
Is the solution to switch the order of ||, to try getWrappedCfiRelativeToContent before getWrappedCfi or will that cause trouble?

**Comment by danielweck** [comment]
Also related: https://github.com/readium/readium-shared-js/issues/345
