### ISSUE TITLE
ResizeSensor (replaces FontLoader), visible content flicker before PAGINATION_CHANGED event

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#354]
TEST LINKS
- "accessible EPUB3" e-book (from https://github.com/readium/readium-js-viewer/tree/develop/epub_content/accessible_epub_3 )
- `ch02.xhtml` "Chapter 2. Building a Better EPUB: Fundamental Accessibility" ( https://rawgit.com/readium/readium-js-viewer/develop/epub_content/accessible_epub_3/EPUB/ch02.xhtml )
- `goto` URL query parameter references the HTML heading entitled "SVG" ( https://rawgit.com/readium/readium-js-viewer/develop/epub_content/accessible_epub_3/EPUB/ch02.xhtml#_svg )

Firebase:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2635343%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bbuilding_a_better_epub%5D%2F10%2F50%2F2%5B_svg%5D%2C%2F1%3A0%2C%2F1%3A3%22%7D

Surge:
https://readium.surge.sh/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2635343%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bbuilding_a_better_epub%5D%2F10%2F50%2F2%5B_svg%5D%2C%2F1%3A0%2C%2F1%3A3%22%7D

Just out of interest, here is a build of "custom OpenDyslexic font" (feature branch, based on develop):
https://readium-fonts.surge.sh/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2635343%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bbuilding_a_better_epub%5D%2F10%2F50%2F2%5B_svg%5D%2C%2F1%3A0%2C%2F1%3A3%22%7D

**Comment by danielweck** [comment]
Using Chrome on Windows 10 (similar behaviour in OSX).
No "developer tools" open, to avoid unintentionally disabling the browser cache during testing.

1) Notice the initial flicker when the page loads. The "SVG" term should temporarily highlight in yellow, that's normal (visual indicator for the `goto` URL query parameter)
2) "turn" pages until the next chapter is loaded ("Getting Around: Navigating an EPUB"). When the browser cache is disabled (either because of HTTP headers or because of the opened "developer tools"), the paragraphs of text appear blank for a moment, then the font face is loaded and rendered inside the CSS boxes.
3) "turn" the page left, to get back to the previous chapter. The end of the document should be displayed, but instead the beginning briefly appears, then the content flickers, then the end of the chapter is correctly shown.

**Comment by danielweck** [comment]
@olivierkorner

**Comment by rkwright** [comment]
@danielweck   This is now fixed, is it not?

**Comment by danielweck** [comment]
Yes, this is now fixed. If there is still flicker (as with the links above in some browser on some particular platform), it is most likely due to the fact that the webview refreshes the dimensions of the loaded document just outside of / pass the debounced time period, so not a Readium bug per-say. We could spend a lot of time tweaking the timing configuration, but this would depend on many factors (large test matrix on browser / platforms).
I am closing this issue now.
