### ISSUE TITLE
package.json has "jquerySizes" instead of correct "jquery-sizes", causing yarn to install module with wrong directory name and breaking build

### ISSUE THREAD

**Issue by da70** [readium/readium-shared-js#356]
Incorrect module name in package.json: "jquerySizes" should be "jquery-sizes"

#### Related issue(s) and/or pull request(s)
#355

#### Expected Behaviour

When installing dependencies using [yarn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiemJKy0ODQAhVDW5AKHfcbCV0QFggcMAA&url=https%3A%2F%2Fyarnpkg.com%2F&usg=AFQjCNFroCU9gpWAHS2N0ZdHNYurDzRu_w&sig2=1Q8ecPVlHZ557l1rWf3iDA), should create directory `node_modules/jquery-sizes/` instead of `node_modules/jquerySizes/`.

`npm run dist` should then run successfully to completion.

#### Observed behaviour

Running `yarn` installs the module in `node_modules/jquerySizes/` instead of `node_modules/jquery-sizes/`, because the dependency is incorrectly named in the `package.json` file.

`npm run dist` then fails with error:

```shell

...

========>
========> RJS bootstrap ...
========>

...

Plugins bundle config:
../../build-config/RequireJS_config_plugins_multiple-bundles.js
[ '../build-config/RequireJS_config_common.js',
  '../build-config/RequireJS_config_multiple-bundles.js',
  '../../build-config/RequireJS_config_plugins.js',
  '../../build-config/RequireJS_config_plugins_multiple-bundles.js',
  '../../build-config/RequireJS_config_common.js',
  '../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../build-config/RequireJS_config_common.js',
  '../../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../../build-config/RequireJS_config_multiple-bundles_external-libs.js',
  '../../../../build-config/RequireJS_config_common.js',
  '../../../../build-config/RequireJS_config_multiple-bundles.js' ]
Error: Error: ENOENT: no such file or directory, open '/Applications/MAMP/htdocs/readium-js-viewer-master/readium-js/readium-shared-js/node_modules/jquery-sizes/lib/jquery.
sizes.js'
    at Object.fs.openSync (fs.js:557:18)

...
```

#### Steps to reproduce

Pre-requisite: install [Yarn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiirffi0-DQAhXJlJAKHYAWDZcQFggcMAA&url=https%3A%2F%2Fyarnpkg.com%2F&usg=AFQjCNFroCU9gpWAHS2N0ZdHNYurDzRu_w&sig2=iyL1FL-MBKfO6z3TiIM0-g)

1. `git clone git@github.com:readium/readium-shared-js.git`
2. `cd readium-shared-js`
3. `yarn`
4. Confirm that `jquery-sizes` module directory is named `node_modules/jquerySizes/`, after the incorrect name in `package.json`.

To verify that this breaks `npm run dist` of the viewer itself, go to existing `readium-js-viewer` and do the steps inside the `readium-shared-js` sub-module and then run the dist build.

### Product

* Readium cloud reader app
  * `master` branch as of [71df2031ba26c81ac50d2214b2f45072b9f92b39](https://github.com/readium/readium-shared-js/commit/71df2031ba26c81ac50d2214b2f45072b9f92b39).

#### Additional information

Currently, the `package.json` file contains this:

```json
  "devDependencies": {
    "jquerySizes": "bramstein/jsizes",
```

The dependency name "jquerySizes" should be "jquery-sizes" to match the `name` field in that module's `package.json` (written by Daniel Weck of Readium, in fact).  See [jsizes/package.json - line 2](https://github.com/bramstein/jsizes/blob/6a13348ed8a8d7a61bd2680d4779190386d9a4c9/package.json#L2).

When `npm install` is run and `npm` is creating the subdirectory in `node_modules/`, it correctly ignores the "jquerySizes" module name given in `devDependencies` and instead uses the `name` field in target Github repo's `package.json`, so that the resulting module directory is `node_modules/jquery-sizes/`.

However, we are going to start using [yarn](https://yarnpkg.com/) for dependency management for our custom build of ReadiumJS viewer, in order to ensure 100% reproducibility of the build, and to protect ourselves from build errors resulting from bugs such as [Fix version of node module cpy #44](https://github.com/readium/readium-cfi-js/pull/44), which disabled our build when it surfaced earlier in the year.  `npm shrinkwrap` fails for both `readium-js` and `readium-shared-js` repos, whereas `yarn` is able to successfully create dependency lock files.  The plan is to create the `yarn.lock` files for `readium-js-viewer` and each of its sub-modules and check them into our ReadiumJS viewer builder repo so we can have reproducible builds.

`yarn` does not install the dependency with the correct name, instead creating directory `node_modules/jquerySizes/`.  I temporarily changed "jquerySizes" to the correct "jquery-sizes" in the `package.json` file and re-installed using `yarn` and was able to re-build our ReadiumJS viewer successfully after that.

`yarn` behavior in this edge case is arguably a bug as `yarn` was designed to be compatible with `npm`, so I might end up submitting a PR to that project or opening an issue there as well.

**Comment by danielweck** [comment]
Thanks for your feedback regarding `npm shrinkwrap`. We've talked about this before, it would be great to "lock" the NPM dependencies in the master branch, as this is the branch used to tag official "stable" releases.

Related issue:
https://github.com/readium/readium-js-viewer/issues/432

**Comment by danielweck** [comment]
Thank you for reporting the `jQuerySizes` vs. `jquery-sizes` naming problem! I will comment in your Pull Request.
https://github.com/readium/readium-shared-js/blob/develop/package.cson#L115

**Comment by danielweck** [comment]
PS: some time ago there was a similar issue with URIjs / urijs:
https://github.com/readium/readium-js-viewer/issues/431
https://github.com/readium/readium-shared-js/commit/9a3e71ac22b5e4b326c5da9fecbbe5f24f81cf27

**Comment by danielweck** [comment]
Fixed, see comments in the original PR:
https://github.com/readium/readium-shared-js/pull/355#issuecomment-265369531

Thank you @da70 ! :)

**Comment by da70** [comment]
Thanks for getting the fix in so quickly, and for linking to [readium/readium-js-viewer#432](https://github.com/readium/readium-js-viewer/issues/432), I can make some comments there about `yarn`.

**Comment by da70** [comment]
@danielweck, would it be possible to update submodule references so that it gets into `master` for the main `readium-js-viewer` project?  Currently the submodule "chain" links to the `readium-shared-js` commit that comes before this fix.

**Comment by danielweck** [comment]
Yes, Git submodules are a maintenance headache!
Please explicitly `git checkout` into your desired branch tip / HEAD.
There are a bunch of commands listed in the README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md#git-initialisation

**Comment by da70** [comment]
I can imagine the tedium of keeping submodules in sync, yes! :)
I guess I was thinking subconsciously that the submodule reference updates were a "blessing" of a particular combination of the submodule commits, i.e. the dev team considered them as working correctly together.  I do in fact already do the initialization steps in the README, and for production build s go further and checkout into detached HEAD the particular commits.
I'll go ahead and checkout this fix commit for the build, since it seems it should be fine for current `master` of main repo.
Thanks.

**Comment by danielweck** [comment]
You are absolutely correct in assuming that the original goal was (still is) to maintain submodule references in such a way that the tip of a given branch is always targeted (so that a git clone with submodule update --init --recursive automatically synchronizes the source tree, even if in detached HEAD mode). Unfortunately the Git cherry-pick (hotfix) is created on top of an existing release tag, so strictly-speaking we should also update the tags in the entire chain of Git modules ... 
A more manageable solution would be to use NPM packages with semver instead.

**Comment by da70** [comment]
I see, yes, that would be a hassle.
I've gone ahead and just checked out the commit in detached HEAD.
Have found a couple more dependencies that could use name corrections, will create a ticket for those and a PR with a CSON file change.
Same issue, `npm run dist` breaks because `yarn` is using the name given in the Readium package.json as opposed to the "name" property in the forked repo's package.json.
