### ISSUE TITLE
package.json has "CSSOM" instead of correct "cssom", causing yarn to install module with wrong directory name

### ISSUE THREAD

**Issue by da70** [readium/readium-shared-js#362]
Incorrect module name in package.json: "CSSOM" should be "cssom"

#### Related issue(s) and/or pull request(s)
#356 
PR: #363

#### Expected Behaviour

When installing dependencies using [yarn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiemJKy0ODQAhVDW5AKHfcbCV0QFggcMAA&url=https%3A%2F%2Fyarnpkg.com%2F&usg=AFQjCNFroCU9gpWAHS2N0ZdHNYurDzRu_w&sig2=1Q8ecPVlHZ557l1rWf3iDA), should create directory `node_modules/cssom/` instead of `node_modules/CSSOM/`.

See also #356.  It is unknown if this would cause a problem during build.  Depends on whether any code references this file path and whether the filesystem is case-sensitive or not.  Mac OS X by default is not case-sensitive, but can be made to be.  There there are *nix and Windows systems to consider.

#### Observed behaviour

Running `yarn` installs the module in `node_modules/CSSOM/` instead of `node_modules/cssom/`, because the dependency is incorrectly named in the `package.json` file.

#### Steps to reproduce

Pre-requisite: install [Yarn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiirffi0-DQAhXJlJAKHYAWDZcQFggcMAA&url=https%3A%2F%2Fyarnpkg.com%2F&usg=AFQjCNFroCU9gpWAHS2N0ZdHNYurDzRu_w&sig2=iyL1FL-MBKfO6z3TiIM0-g)

1. `git clone git@github.com:readium/readium-shared-js.git`
2. `cd readium-shared-js`
3. `yarn`
4. Confirm that `cssom` module directory is named `node_modules/CSSOM/`, after the incorrect name in `package.json`.

### Product

* Readium cloud reader app
  * `master` branch as of [71df2031ba26c81ac50d2214b2f45072b9f92b39](https://github.com/readium/readium-shared-js/commit/71df2031ba26c81ac50d2214b2f45072b9f92b39).

#### Additional information

Currently, the `package.json` file contains this:

```json
  "devDependencies": {
    ...
    "CSSOM": "danielweck/CSSOM#gh-pages"
```

The dependency name "CSSOM" should be "cssom" to match the `name` field in that module's `package.json`.  See [package.json - line 6](https://github.com/danielweck/CSSOM/blob/gh-pages/package.json#L6).

See "Additional information" section of #356 for more discussion.

**Comment by danielweck** [comment]
Fixed by https://github.com/readium/readium-shared-js/pull/363
