### ISSUE TITLE
Highlights: jQuery touch event "undefined" bug

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#365]
https://github.com/readium/readium-shared-js/blob/develop/plugins/highlights/models/group.js#L376
`var lastTouch = _.last(e.changedTouches);`
`changedTouches` is undefined, should be `e.originalEvent.changedTouches`
(`e` is jQuery event)

**Comment by danielweck** [comment]
CC @JCCR

**Comment by danielweck** [comment]
Reported by @nimisis at https://github.com/readium/SDKLauncher-iOS/issues/91#issuecomment-271559455

**Comment by danielweck** [comment]
Also reported by @kivuto

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-shared-js/commit/5c24c38663a0dca7d09ca225c4977722262c2e7b

**Comment by danielweck** [comment]
Note: was fixed in Mantano's PR!
https://github.com/readium/readium-shared-js/pull/237/files#diff-652783b831d1c9386c3194019f6820d1L377

**Comment by sercanl** [comment]
Hi @danielweck ,

I wonder if this commit (5c24c38) is still valid in later versions of Readium. I looked it up in various releases, but couldn't find it. I am struggling with a iOS touchend problem which is triggered from **group.js** file. ( inside boundHighlightCallback(...) )

Error message in console: TypeError: undefined is not an object (evaluating 's.pageX')

**Comment by danielweck** [comment]
The "highlight" plugin (previously-named "annotation") was an experiment implemented by @jccr / @evidentpoint (if I remember correctly) and although it showed a lot of promise, it was incomplete and unmaintained. So the pragmatic solution was to replace it with the "hypothesis" plugin which delegates the entire functionality to the cloud service https://web.hypothes.is
