### ISSUE TITLE
Last page of a spine item is cut off

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#369]
#### Related issue(s) and/or pull request(s)
#193  
readium-js-viewer#375  
This issue may be a duplicate.  Appears fixed in current build, but is easily reproduced in 2.24.0 Logging it here just for completeness sake.

#### Expected Behaviour
Should render all of the spine items completely

#### Observed behaviour
Instead, a small portion (last page?) of the the spine items are not rendered.

#### Steps to reproduce
1. Load the test book in 2.24 (current in store as of 31 January)
2. Navigate to end of chapter
3. Compare to 2.24-Develop or iBooks
4. Note text is missing.

#### Test file(s)
Test file, in Polish, is [here](https://drive.google.com/open?id=0BzaNaBNAB6FjU0l2ZjNhNEc0aUE)

### Product

* Readium Chrome extension
  * latest official version available from the Chrome Web Store 

#### Additional information
None

**Comment by danielweck** [comment]
This was fixed with the replacement of FontLoader with ResizeSensor, now available in the latest official release v0.25
