### ISSUE TITLE
package.json has "ResizeSensor" instead of correct "css-element-queries", causing yarn to install module with wrong directory name and breaking build

### ISSUE THREAD

**Issue by da70** [readium/readium-shared-js#373]
Incorrect module name in package.json: "ResizeSensor" should be "css-element-queries"

#### Related issue(s) and/or pull request(s)
#356 #362
PR: #374 

#### Expected Behaviour

When installing dependencies using [yarn](https://yarnpkg.com/), should create directory `node_modules/css-element-queries/` instead of `node_modules/ResizeSensor/`.

`npm run dist` should then run successfully to completion.

#### Observed behaviour

Running `yarn` installs the module in `node_modules/ResizeSensor/` instead of `node_modules/css-element-queries/`, because the dependency is incorrectly named in the `package.json` file.

`npm run dist` then fails with error:

```shell

...

========>
========> RJS bootstrap ...
========>

...

Plugins bundle config:
../../build-config/RequireJS_config_plugins_multiple-bundles.js
[ '../build-config/RequireJS_config_common.js',
  '../build-config/RequireJS_config_multiple-bundles.js',
  '../../build-config/RequireJS_config_plugins.js',
  '../../build-config/RequireJS_config_plugins_multiple-bundles.js',
  '../../build-config/RequireJS_config_common.js',
  '../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../build-config/RequireJS_config_common.js',
  '../../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../../build-config/RequireJS_config_multiple-bundles_external-libs.js',
  '../../../../build-config/RequireJS_config_common.js',
  '../../../../build-config/RequireJS_config_multiple-bundles.js' ]
Error: Error: ENOENT: no such file or directory, open ''/Applications/MAMP/htdocs/readium-js-viewer/readium-js/readium-shared-js/node_modules/css-element-queries/src/ResizeSensor.js'
    at Error (native)
```

#### Steps to reproduce

Pre-requisite: install [Yarn](https://yarnpkg.com/)

1. `git clone git@github.com:readium/readium-shared-js.git`
2. `cd readium-shared-js`
3. `yarn`
4. Confirm that `css-element-queries` module directory is named `node_modules/ResizeSensor/`, after the incorrect name in `package.json`.

To verify that this breaks `npm run dist` of the viewer itself, go to existing `readium-js-viewer` and do the steps inside the `readium-shared-js` sub-module and then run the dist build.

### Product

* Readium cloud reader app `master` and `develop` branches

#### Additional information

Currently, the `package.json` file contains this:

```json
  "devDependencies": {
    ...
  "ResizeSensor": "danielweck/css-element-queries"
```

The dependency name "ResizeSensor" should be "css-element-queries" to match the `name` field in that module's `package.json`.  See [package.json - line 2](https://github.com/danielweck/css-element-queries/blob/master/package.json?#L2).

See "Additional information" section of #356 for more discussion.

**Comment by danielweck** [comment]
Fixed by PR: https://github.com/readium/readium-shared-js/pull/374
Thanks!

**Comment by da70** [comment]
Thanks Daniel!
