### ISSUE TITLE
resize sensor breaks highlightplugin in scroll mode

### ISSUE THREAD

**Issue by einarstubhaug** [readium/readium-shared-js#375]
#### version
Readium version 0.25

#### Expected Behaviour
Create a highlight in scroll mode

#### Observed behaviour
Readium fails, because it generates the lastVisibleCfi on the resize-sensor div (it is appended to the body element). The cfi generated in my test case is: "/4/NaN/NaN/2". Seems like the blacklisting of "resize-sensor" only partially works?

#### Steps to reproduce
1) In scroll mode (my settings are ({syntheticSpread: 'single', scroll: 'scroll-doc'})), add highlight.

**Comment by rkwright** [comment]
@JCCR @olivierkorner   Comments guys?

**Comment by danielweck** [comment]
Also note that `TypeError: undefined is not an object (evaluating 'this.context.paginationInfo().isVerticalWritingMode')` still occurs in the scroll view when attempting to create highlights using the ReadiumJS plugin (which is currently disabled in the Chrome app, but enabled in the developer cloud reader builds).
For example, open this link, and change the view settings (e.g. scroll document) via the options dialog:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2635343%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bbuilding_a_better_epub%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D
...then create a highlight, to select some text and attempt to create a bookmark link.

See:
https://github.com/readium/readium-shared-js/issues/280
and 
https://github.com/readium/readium-shared-js/issues/315

**Comment by danielweck** [comment]
I am able to reproduce the `NaN` CFI error (Safari OSX).

**Comment by JCCR** [comment]
@einarstubhaug 
I submitted a fix for the `NaN` CFI error.
#380 
Once that gets in give it another shot. I'm hoping this fixes your issue with the highlight plugin, but if it doesn't feel free to make a new issue.

**Comment by einarstubhaug** [comment]
Now it works, excellent!
