### ISSUE TITLE
MathJax and ResizeSensor interaction (several page reloads / relayout)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#377]
Test link:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.github.io%2Freadium-js-viewer%2Fepub_content%2FHales-Motivic-Measure&goto=%7B%22idref%22%3A%22c4%22%2C%22elementCfi%22%3A%22%2F4%2F4%2F2%2C%2F1%3A1%2C%2F1%3A2%22%7D

**Comment by rkwright** [comment]
@danielweck  Just tested with 0.28-alpha and it appears fixed.  Can you confirm?

**Comment by danielweck** [comment]
Agreed. The debounced "pagination update" function collapses multiple refreshes into a single pass. I do not see any flickering in Chrome or Safari on OSX.
