### ISSUE TITLE
Some problems when rendering: yellow mark and back to first page

### ISSUE THREAD

**Issue by prsolucoes** [readium/readium-shared-js#389]
Hi,

I have two major problems. Im using the last version of all. 

1 - When change font size a yellow mark appear over the text.
2 - When change font size sometime it back to first page.

I made a video to show this two issues:
https://youtu.be/cTg0Ox9HiWU

**Comment by prsolucoes** [comment]
Problems times:

TIME 0:56 > on change font it show yellow mark
TIME 1:05 > on change font it back to first page

**Comment by danielweck** [comment]
The temporary yellow character mark is a debug statement related to the CFI "bookmark" (backup of the reading location). It should be deactivated in production builds of the cloud / web reader. I will take a look.

**Comment by danielweck** [comment]
Please set `DEBUG` to `false` in `reader_view`'s `debugBookmarkData()`:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L1021

**Comment by prsolucoes** [comment]
Ok, but it will be true forever? Or it will be changed in master branch?

**Comment by prsolucoes** [comment]
I have commented and nothing change. I have removed entire functions content and nothing changed.

<img width="487" alt="screenshot 2017-05-25 12 44 19" src="https://cloud.githubusercontent.com/assets/395096/26457837/e32ca600-4147-11e7-91ca-e8d1e13db055.png">

The yellow box still appear.

**Comment by prsolucoes** [comment]
Tested on device and simulator. I check the simulator js files and the function only have the signature without body, to see if dont is a cache, and it is as spected.

**Comment by prsolucoes** [comment]
Hi, problems solved. The HTML is using "readium-shared-js_all.js", that is a compiled file with all others JS files. So i changed this bundle file and now it is working. Thanks. Can be closed.

**Comment by danielweck** [comment]
Yep, you need to invoke `npm run http` in `readium-js-viewer` in order to test the raw source files (individual AMD modules). Otherwise `npm run build` (or `npm run dist+sourcemap`) must be used to update the compiled bundles in the `build-output` / `dist` folders.

**Comment by danielweck** [comment]
As for the `master` branch: yes, we must make sure to disable this next time. There are other verbose DEBUG statements in the console which we could probably disable in "stable" builds / sourcetree.
