### ISSUE TITLE
How to find some reference on current page?

### ISSUE THREAD

**Issue by prsolucoes** [readium/readium-shared-js#391]
Hi,

How to find some reference on current page?

I want bookmark that page, but when a bookmark was found for that "page", i want show a sticker, like Kindle makes. How i can check it? I think that is something that we do with bookmark data and content cfi data.

Can anyone help me?

Thanks.

**Comment by danielweck** [comment]
Register a listener to the `PAGINATION_CHANGED` event, within which you iterate through the list of stored "bookmarks", until you find one or more that returns `true` to `reader_view.isVisibleSpineItemElementCfi()`, at which point you can then display a "bookmark" tag on the page.

**Comment by prsolucoes** [comment]
Nice. I will post my code here if anyone need help in future:

```
func updateBookmarkOnCurrentPage() {
        let bookmarkList = BookmarkService.findAllByEbookIdOrderByCreatedAtDesc(ebookId: ebook.id!)
        
        showBookmarkSticker(show: false)
        
        if bookmarkList.count > 0 {
            for bookmark in bookmarkList {
                executeJavaScript(javascript: String(format: "ReadiumSDK.reader.isVisibleSpineItemElementCfi('%@', '%@')", bookmark.bookmarkIdRef!, bookmark.bookmarkCFI!), completionHandler: { (response, error) in
                    if let response = response as? Bool {
                        if response == true {
                            DispatchQueue.main.async {
                                self.showBookmarkSticker(show: true)
                            }
                        }
                    }
                })
            }
        }
}
```
