### ISSUE TITLE
'yarn' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nandita121189** [readium/readium-shared-js#394]
Hello,

While running `npm run build` task, I get an error the following error 
`'yarn' is not recognized as an internal or external command`

The problem is that the `prebuild` task(which is called before the build task) has a `clean ` task in it which uses `yarn --version` command. As my machine didnt have yarn installed I was unable to build the project.

Although the documentation mentions that `yarn `is optional, I could only build the project after running the following command
`npm install yarn -g`

So is yarn mandatory or is it some bug ? Please suggest what should I do.

Thanks

**Comment by danielweck** [comment]
oh, good point. I will fix this.

**Comment by danielweck** [comment]
Fixed in the develop branch, many thanks for reporting!!
