### ISSUE TITLE
Under certain conditions MO player speaks out the letter 'O' via TTS on iOS

### ISSUE THREAD

**Issue by JCCR** [readium/readium-shared-js#400]
#### Expected Behaviour
Play MO media without speaking the letter 'O' out loud

#### Observed behaviour
When hitting the play button on iOS under certain conditions (the touchInit codepath is used) then TTS plays speaking the letter 'O' outloud.

#### Steps to reproduce
1. Grab an iOS device running Readium
2. Make sure `_mediaOverlayPlayer.touchInit();` is called somewhere during initialization of ReaderView
3. Play a chapter with Media Overlay content
4. Listen closely to see if you hear an anomalous TTS rendering that sounds like the letter 'O'

### Product
* Readium cloud reader app
  * latest development build uploaded at https://readium.firebaseapp.com
  * Mobile Safari
  * iOS

#### Additional information
The culprit is this line here:
https://github.com/readium/readium-shared-js/blob/develop/js/views/media_overlay_player.js#L938

**Comment by danielweck** [comment]
Fixed via: https://github.com/readium/readium-shared-js/pull/401
