### ISSUE TITLE
no more readium_plugin_highlights in build-readium-shared-js_all.js

### ISSUE THREAD

**Issue by fjansen** [readium/readium-shared-js#403]
I've update the shared js projet from develo branch and copy the build-output/_single-bundle/readium-shared-js_all.js in my project and i've a big surprise, nothing run.
There is no more "readium_plugin_highlights" in the js file. Is it an error in the git repository, or the plugin was deleted from the projet ?
Thank's
Fabrice

**Comment by danielweck** [comment]
Correct. The plugins configuration determines what gets built:
https://github.com/readium/readium-shared-js/blob/develop/plugins/plugins.cson
The Hypothesis plugin is now activated by default, but you can disable it, or load the highlight plugin side by side if you want.
