### ISSUE TITLE
First visible element check in cfi navigation logic broken in scroll view

### ISSUE THREAD

**Issue by wisfan** [readium/readium-shared-js#405]
#### This issue is a Bug
Minor regression issue due to offsets not being applied when normalizing rectangles for visibility checking. 

#### Related issue(s) and/or pull request(s)
PR #406 
Related to changes in [PR#395](https://github.com/readium/readium-shared-js/pull/395)

#### Observed behaviour
Result of `findFirstVisibleElement` in CfiNavigationLogic is always the first child element of the body when using ScrollView. 

#### Steps to reproduce
Invoke `ReaderView.bookmarkCurrentPage` while using scroll view with any book. The result does not vary with scroll position.

### Product
Only users of current develop branch, does not affect master

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-shared-js/issues/405
Many thanks for spotting this!!
