### ISSUE TITLE
Native apps: Hypothesis plugin is activated by default in the build-output of shared-js

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#418]
ReadiumSDK launcher apps include `readium-shared-js`via submodule in order to fetch `./build-output/` single or multiple AMD bundles, unfortunately the Hypothesis plugin is currently activated in order for the cloud reader automatic deployment to Firebase / Surge (via TravisCI) to contain the annotation feature.

**Comment by danielweck** [comment]
See: https://github.com/readium/readium-js-viewer/issues/657#issuecomment-337926999

**Comment by rkwright** [comment]
@danielweck Isn't this now resolved with the changes to and release of 0.28?  If not, what is there left to do here?

**Comment by danielweck** [comment]
Closed via resolution of https://github.com/readium/readium-js-viewer/issues/658
