### ISSUE TITLE
Trailing Blank Pages [iOS WKWebView using readium-shared-js library]

### ISSUE THREAD

**Issue by milonghetto** [readium/readium-shared-js#420]
Whenever going from page to page and approaching the end of a chapter in a subset of ePubs, the chapter will display extra blank pages.  These blank pages will increase in numbers as the chapters progressed within a book (i.e.:  Chapter 2 would have 5 blank pages, Chapter 3 would have 7 blank pages, Chapter 4 would have 12 blank pages, etc., etc.)

This is noticeable on ePubs which would have a structure above the chapter level (i.e.:  Part 1, Part 2)

#### Expected Behaviour
No blank pages at the end of a chapter.

#### Observed behaviour
Readium shows blank pages in WKWebView under iOS 10.x and iOS 11.x

#### Steps to reproduce
1. Load book into WKWebView using the Readium shared JS libraries (readium-shared-js)
2. Move through the ePub from page to page until approaching end of the chapter.
3. Blank pages will appear right after the actual last page for the chapter (number of blank pages will vary)

#### Test file(s)
Please, contact jtablada@penguinrandomhouse.com for ePub to use.

### Product
* readium-shared-js library on iOS.

**Comment by danielweck** [comment]
Hello,
are you using the iOS ReadiumSDK "launcher app"? ( https://github.com/readium/SDKLauncher-iOS )
Are you able to reproduce this bug in the cloud reader? ( https://readium.firebaseapp.com ) You can drag+drop your EPUB file into the browser window, as long as the file isn't too large (as it will be entirely loaded in memory).

**Comment by milonghetto** [comment]
Hi!

We are not using the iOS ReadiumSDK "launcher app." We are currently using the Readium library "readium-shared-js" for iOS.

The ePub is much too large to be used on the Cloud reader which you have suggested; however, if you would like to take a look at the ePub, we will be more than willing to share the ePub as well as our iOS code for you to look at it via Box.

**Comment by rkwright** [comment]
@milonghetto  Can you give us an idea of how you are deploying your Reader?  Not sure it is critical, but any additional information may be useful.  
I also sent an email to jtablada.

**Comment by rkwright** [comment]
Upgrading to current version (0.28) seems to have fixed this issue.
