### ISSUE TITLE
Chapters getting truncated [iOS - readium-shared-js library]

### ISSUE THREAD

**Issue by milonghetto** [readium/readium-shared-js#421]
Whenever flipping pages through a chapter and approaching the end the chapter in a subset of ePubs, the chapter may be truncated (the last page(s) will not be displayed).

This is noticeable on ePubs which would have a structure above the chapter level (i.e.: Part 1, Part 2)

This issue is a Bug

Related issue(s) and/or pull request(s)

Expected Behaviour

All pages for a chapter should be displayed.

Observed behaviour

Readium displays a page which may be short several paragraph of what the actual chapter should be in WKWebView under iOS 10.x and iOS 11.x

Steps to reproduce

Load book into WKWebView using the Readium shared JS libraries (readium-shared-js)
Move through the ePub from page to page until approaching end of the chapter.  98% of the chapter's text is displayed with the remainder missing.

Test file(s)

Please, contact jtablada@penguinrandomhouse.com for ePub to use.

Product

readium-shared-js library on iOS.

**Comment by danielweck** [comment]
Hello,
are you using the iOS ReadiumSDK "launcher app"? ( https://github.com/readium/SDKLauncher-iOS )
Are you able to reproduce this bug in the cloud reader? ( https://readium.firebaseapp.com ) You can drag+drop your EPUB file into the browser window, as long as the file isn't too large (as it will be entirely loaded in memory).

**Comment by milonghetto** [comment]
Hi!

We are not using the iOS ReadiumSDK "launcher app."  We are currently using the Readium library "readium-shared-js" for iOS.

The ePub is much too large to be used on the Cloud reader which you have suggested; however, if you would like to take a look at the ePub, we will be more than willing to share the ePub as well as our iOS code for you to look at it via Box.

**Comment by JayPanoz** [comment]
For the record, it kinda rings a bell to me as I’ve regularly encountered the same bug in CloudShelf Reader with some files. 

Now, I must admit retrieving those files will be tricky as it was several months ago but please feel free if you need more samples, @danielweck, I’ll then retest a bunch if it can help.

**Comment by rkwright** [comment]
Upgrading to current version (0.28) seems to have fixed this issue.
