### ISSUE TITLE
Use of reserved word "package"

### ISSUE THREAD

**Issue by JCCR** [readium/readium-shared-js#431]
Forwarding this issue from an outside contributor:

> The word "package" is a reserved word in JavaScript (https://www.w3schools.com/js/js_reserved.asp). Please rename the variables currently named "package" to "pkg" in the following locations (locations based on develop branch source):
> 
> src/js/models/media_overlays.js lines 39 and 47 (instance variable usage)
> src/js/views/reader_view.js lines 1506 and 1507

**Comment by rkwright** [comment]
@JCCR Can you follow up with B&T to see why this is important? And how important?

**Comment by JCCR** [comment]
Fixed in #432
