### ISSUE TITLE
calculatePageIndexDeltaByRectangles has wrong logic calculating pageIndex

### ISSUE THREAD

**Issue by jplaitin** [readium/readium-shared-js#437]
cfi_navigation_logic.js function calculatePageIndexByRectangles returns one too high page index if Math.round will actually rounds up. So instead of using round in this case using floor should fix this.

This issue will show when using inner links. Sometimes inner link opens to correct page and sometimes it opens one page further than it was supposed to open. 
This issue is a Bug
*What you expected Readium to do...*
Calculate pageIndex with floor instead of round

**Comment by danielweck** [comment]
Thank you for reporting this. We must review the algorithm and we could even make an decision based on that alone (assuming we find some obvious arithmetic error). But ideally we should also be able to reproduce the bug, if possible with the cloud reader so we can link to it. Do you have suggestions as to: which EPUB, which viewport dimensions? (etc.)

**Comment by jplaitin** [comment]
Any book with innerlinks that aren't at start of the spine should work if you change font size a bit. Link should point at the end of a page (this should cause that round up "error" to happen) and spine should be split to multiple pages.

**Comment by danielweck** [comment]
@JCCR have you experienced this bug?

**Comment by JCCR** [comment]
@danielweck @jplaitin 
I'm looking into this.
Thanks for the report.

**Comment by JCCR** [comment]
![2000 years later](https://user-images.githubusercontent.com/5132652/38117391-83041f78-3369-11e8-8c71-0594ef712e2b.jpg)

I can confirm the change to `Math.floor` from `Math.round` fixes this regression.
Thanks for the report @jplaitin

**Comment by danielweck** [comment]
Closed via https://github.com/readium/readium-shared-js/pull/444
