### ISSUE TITLE
Build output: UMD bundle

### ISSUE THREAD

**Issue by JCCR** [readium/readium-shared-js#439]
We need a library bundle output that's wrapped in [UMD](https://github.com/umdjs/umd)
Unlike other bundle outputs this one should not depend on or include a built-in RequireJS loader such as almond.js. This increases the library's portability and allows it to be easily imported by various module and bundler systems. One such example is with Webpack/Browserify importing the library as CommonJS. This was not available out of the box with other build outputs.

#### Proposed solution:
- Introduce a new build output called "umd bundle"
- The creation of the UMD output is based on the output from the "single-bundle" which is processed with a tool called [AMDClean](https://github.com/gfranko/amdclean/)
- Implement this as an additional step to our build scripts that use the r.js optimizer (our existing bundler)
- Keep the rest of our build system intact

**Comment by danielweck** [comment]
UMD supports CommonJS (in addition to AMD, window global, etc.), therefore published libs such as CFI (`readium-cfi-js`) could potentially be distributed with the appropriate `main` field in `package.json`. What about `jsnext:main` / `module` to discover native ECMAScript modules? Is this on your radar? (just asking out of curiosity)

**Comment by JCCR** [comment]
@danielweck 
Yes, possibly as another bundle type.

**Comment by danielweck** [comment]
Is this now fixed, Juan?

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-shared-js/pull/441
(correct me if I am wrong, Juan)
