### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by DougsAraujo** [readium/readium-shared-js#448]
The hyphotesis plugin when activated in the cson file works normally, however the plugin highlights does not, it is enabled but does not mark the selection.

# You may add the plugins that should be included here.
plugins: [
 #  'highlights'
 #  'example' 
 
    'highlights' # Loader for the Hypothesis annotator - http://hypothes.is
    'hypothesis' 	 	
]

# you may override this configuration by creating a file called plugins-override.cson, e.g.:
#plugins:
#    include: [
#        'example'
#    ]
#    exclude: [
#      'highlights'
#    ]

**Comment by danielweck** [comment]
In the `develop` branch (which will be merged into `master` at the next official tagged release), `plugins/highlights` was removed by this Pull Request: https://github.com/readium/readium-shared-js/pull/446

The team of core contributors recently agreed to remove the out-of-date `highlights` plugin. This experimental "annotation" code was relying on Rangy (or to be precise: a fork of it tweaked by @JCCR, the original plugin implementer). Rangy was causing problems in the build system (see https://github.com/readium/readium-shared-js/issues/445 ), and as the core Readium projects (Chrome app, cloud reader, native apps, etc.) do no make use of the functionality provided by the `highlights` plugin, it was decided to simplify the codebase and build system by removing both Rangy and the `highlights` plugin (note that Rangy was also used in a few other places, notably for an experimental / unused Media Overlays feature).

So,  you *can* re-instate `plugins/highlights` and Rangy in your own fork, by simply reverting the git commits (`git revert`) in the following PRs:
https://github.com/readium/readium-shared-js/pull/446
https://github.com/readium/readium-js/pull/190
https://github.com/readium/readium-js-viewer/pull/695
