### ISSUE TITLE
Inconsistent word-spacing across platforms (font metrics?)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#51]
From Talha Yalta talhayalta@gmail.com:

Still, as can be seen in the attached file, Readium has (I think) word
spacing problems. This is a serious issue because the looks of the
fixed-layout book can be seriously affected by it, resulting in text
cutoff etc.

After testing the attached file with Azardi, Readium in Windows 7 and
Readium in Snow Leopard; it seems to me that
word spacing in Readium (Win) < Azardi < Readium (OSX)

The difference is probably small but it is enough to shift a single
word to the next line. These shifts can in turn result in significant
changes to the text layout, even in not-too-long paragraphs.

Bugzilla:
https://app.devzing.com/Readium/bugzilla/show_bug.cgi?id=71

**Comment by JayPanoz** [comment]
Re-checking R1-related issues for ReadiumCSS and I would have loved to give it a look but the screenshots are probably lost, aren’t they? 

> The difference is probably small but it is enough to shift a single word to the next line. These shifts can in turn result in significant changes to the text layout, even in not-too-long paragraphs.

From this I can only assume that’s just to be expected. 

Layout/H&J/spacing can vary greatly across browsers, platforms, etc. so it’s pretty much impossible to get exactly the same result everywhere. I know it’s been a constant complaint in fixed-layout but that’s an idiosyncrasy of the web platform – InDesign even tried to fight that by treating FXL as PDF but created an unsolvable issue in doing so, unless they completely re-architecture their output…

**Comment by danielweck** [comment]
Yep, let's close this totally obsolete issue.
