### ISSUE TITLE
Error in mlong division MathML test

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#96]
The MathML test in EPUB TestSuite 100 (MathML-027) featuring long division isn't quite right.  The horizontal lines are missing.  Also, the vertical spacing seems over-large.

![longdivision](https://cloud.githubusercontent.com/assets/3025864/3906493/70595fee-22f3-11e4-8f65-0a6c25baa8f0.png)

**Comment by pkra** [comment]
Is this not fixed by now?

**Comment by danielweck** [comment]
Looks good to me:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0100&goto=%7B%22idref%22%3A%22xhtml-mathml-001%22%2C%22elementCfi%22%3A%22%2F4%2F4%2F2%5Bmathml%5D%2C%2F1%3A0%2C%2F1%3A1%22%7D
